export const PRODUCT_IMAGES = {
  "Away Jersey 24/25": "https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Home Jersey 24/25": "https://images.pexels.com/photos/1661338/pexels-photo-1661338.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Club Mug": "https://images.pexels.com/photos/1209462/pexels-photo-1209462.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Beanie Hat": "https://images.pexels.com/photos/1124465/pexels-photo-1124465.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Away Jersey 2024": "https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Home Jersey 2024": "https://images.pexels.com/photos/1661338/pexels-photo-1661338.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Third Kit Jersey": "https://images.pexels.com/photos/1124466/pexels-photo-1124466.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Training Top": "https://images.pexels.com/photos/1311523/pexels-photo-1311523.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Training Jacket": "https://images.pexels.com/photos/1311523/pexels-photo-1311523.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Training Shorts": "https://images.pexels.com/photos/4753987/pexels-photo-4753987.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Club Scarf": "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Football Scarf": "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Team Cap": "https://images.pexels.com/photos/1124465/pexels-photo-1124465.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Fan Hoodie": "https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Match Ball Official": "https://images.pexels.com/photos/47730/the-ball-stadion-football-the-pitch-47730.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Mini Football": "https://images.pexels.com/photos/47730/the-ball-stadion-football-the-pitch-47730.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Goalkeeper Gloves": "https://images.pexels.com/photos/2277980/pexels-photo-2277980.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Shin Guards Pro": "https://images.pexels.com/photos/3621183/pexels-photo-3621183.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Signed Jersey": "https://images.pexels.com/photos/918778/pexels-photo-918778.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Signed Photo Frame": "https://images.pexels.com/photos/918778/pexels-photo-918778.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Stadium Print A3": "https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Stadium Flag": "https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Mini Trophy Replica": "https://images.pexels.com/photos/1884577/pexels-photo-1884577.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Water Bottle": "https://images.pexels.com/photos/1346197/pexels-photo-1346197.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Keyring": "https://images.pexels.com/photos/1191090/pexels-photo-1191090.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Retro Badge Pin": "https://images.pexels.com/photos/1884577/pexels-photo-1884577.jpeg?auto=compress&cs=tinysrgb&w=300",
  "t_shirt": "https://images.pexels.com/photos/428338/pexels-photo-428338.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Evening Midi Dress": "https://images.pexels.com/photos/985287/pexels-photo-985287.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Summer Floral Dress": "https://images.pexels.com/photos/1485031/pexels-photo-1485031.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Office Shift Dress": "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Casual Denim Dress": "https://images.pexels.com/photos/1346187/pexels-photo-1346187.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Maxi Boho Dress": "https://images.pexels.com/photos/1755385/pexels-photo-1755385.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Bodycon Cocktail Dress": "https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Linen Shirt Dress": "https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Wrap Dress Classic": "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Kids Party Dress": "https://images.pexels.com/photos/1620760/pexels-photo-1620760.jpeg?auto=compress&cs=tinysrgb&w=300",
  "Bridesmaid Dress": "https://images.pexels.com/photos/291759/pexels-photo-291759.jpeg?auto=compress&cs=tinysrgb&w=300",
};

export const INITIAL_PRODUCTS = [
  { id: 1, name: "Home Jersey 2024", sku: "JRS-HOME-24", category: "Jerseys", price: 89.99, stock: 45, emoji: "🔴", featured: true, description: "Official 2024 home kit jersey. Premium quality breathable fabric, moisture-wicking technology. Club crest embroidered on chest.", discount: 0, sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Red/White"], material: "100% Polyester", fit: "Regular Fit", care: "Machine wash 30°C", brand: "SCSTix Official", taxPct: 20 },
  { id: 2, name: "Away Jersey 2024", sku: "JRS-AWAY-24", category: "Jerseys", price: 89.99, stock: 32, emoji: "⚪", featured: true, description: "Official 2024 away kit jersey. Lightweight performance fabric with ventilation zones.", discount: 0, sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["White/Blue"], material: "100% Polyester", fit: "Slim Fit", care: "Machine wash 30°C", brand: "SCSTix Official", taxPct: 20 },
  { id: 3, name: "Third Kit Jersey", sku: "JRS-THIRD-24", category: "Jerseys", price: 84.99, stock: 18, emoji: "🔵", featured: false, description: "Limited edition third kit. Bold design with contrast trim, limited run of 500 units.", discount: 0, sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Navy Blue"], material: "100% Polyester", fit: "Regular Fit", care: "Machine wash 30°C", brand: "SCSTix Official", taxPct: 20 },
  { id: 4, name: "Training Jacket", sku: "TRN-JKT-24", category: "Training Wear", price: 64.99, stock: 27, emoji: "🧥", featured: true, description: "Lightweight training jacket with zip pockets. Wind-resistant shell, perfect for matchday warm-up.", discount: 0, sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Red", "Black"], material: "95% Polyester, 5% Elastane", fit: "Athletic Fit", care: "Machine wash 40°C", brand: "SCSTix Official", taxPct: 20 },
  { id: 5, name: "Training Shorts", sku: "TRN-SHT-24", category: "Training Wear", price: 34.99, stock: 41, emoji: "🩳", featured: false, description: "Pro training shorts with elastic waistband and side pockets.", discount: 0, sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Red", "Black", "White"], material: "100% Polyester", fit: "Regular Fit", care: "Machine wash 40°C", waist: "28-38 inches adjustable", brand: "SCSTix Official", taxPct: 20 },
  { id: 6, name: "Football Scarf", sku: "ACC-SCARF-01", category: "Fan Accessories", price: 19.99, stock: 120, emoji: "🧣", featured: true, description: "Knitted team scarf, double-sided club colours. Official merchandise.", discount: 0, sizes: ["One Size"], colors: ["Red/White"], material: "100% Acrylic", length: "150cm", width: "20cm", care: "Hand wash cold", brand: "SCSTix Official", taxPct: 20 },
  { id: 7, name: "Team Cap", sku: "ACC-CAP-01", category: "Fan Accessories", price: 24.99, stock: 85, emoji: "🧢", featured: false, description: "Embroidered team cap with adjustable strap.", discount: 0, sizes: ["One Size (Adjustable)"], colors: ["Red", "Black", "White"], material: "Cotton Twill", fit: "Structured 6-panel", care: "Spot clean only", brand: "SCSTix Official", taxPct: 20 },
  { id: 8, name: "Fan Hoodie", sku: "ACC-HOOD-01", category: "Fan Accessories", price: 54.99, stock: 33, emoji: "👕", featured: true, description: "Premium fan hoodie with kangaroo pocket. Soft fleece lining, printed club crest.", discount: 0, sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Red", "Navy", "Grey"], material: "80% Cotton, 20% Polyester", fit: "Relaxed Fit", care: "Machine wash 30°C", brand: "SCSTix Official", taxPct: 20 },
  { id: 9, name: "Match Ball Official", sku: "EQP-BALL-01", category: "Football Equipment", price: 129.99, stock: 12, emoji: "⚽", featured: true, description: "FIFA approved match ball. Used in official league matches. Thermally bonded panels.", discount: 10, sizes: ["Size 5 (Official)"], colors: ["White/Black/Red"], material: "Synthetic leather, Latex bladder", circumference: "68-70cm", weight: "410-450g", care: "Wipe clean only", brand: "SCSTix Pro", taxPct: 20 },
  { id: 10, name: "Goalkeeper Gloves", sku: "EQP-GLV-01", category: "Football Equipment", price: 44.99, stock: 8, emoji: "🥅", featured: false, description: "Pro goalkeeper gloves with 4mm latex palm. Negative cut for superior grip.", discount: 0, sizes: ["6", "7", "8", "9", "10", "11"], colors: ["Red/Black", "Black/Yellow"], material: "German Latex Palm, Neoprene back", cut: "Negative Cut", care: "Hand wash cold, air dry", brand: "SCSTix Pro", taxPct: 20 },
  { id: 11, name: "Shin Guards Pro", sku: "EQP-SHIN-01", category: "Football Equipment", price: 29.99, stock: 55, emoji: "🛡️", featured: false, description: "Lightweight shin guards with ankle protection. Hard shell with foam backing.", discount: 0, sizes: ["XS (6-9yrs)", "S (9-12yrs)", "M (12-15yrs)", "L (15+yrs)"], colors: ["Black", "Red/Black"], material: "Polypropylene shell, EVA foam", height: "Multiple (see sizes)", care: "Wipe clean", brand: "SCSTix Pro", taxPct: 20 },
  { id: 12, name: "Signed Jersey", sku: "COL-SIG-CAP", category: "Collectibles", price: 249.99, stock: 3, emoji: "✍️", featured: true, description: "Signed by the club captain. Comes with certificate of authenticity and display frame. Limited edition.", discount: 0, sizes: ["L (Display Size)"], colors: ["Red/White (Home)"], material: "Official match jersey with authentic signature", edition: "Limited — only 3 remaining", includes: "Certificate of Authenticity, Display Frame", care: "Keep away from direct sunlight", brand: "SCSTix Collectibles", taxPct: 20 },
  { id: 13, name: "Stadium Print A3", sku: "COL-PRT-01", category: "Collectibles", price: 39.99, stock: 22, emoji: "🖼️", featured: false, description: "A3 art print of the stadium, hand-numbered. Ideal for framing.", discount: 0, sizes: ["A3 (297 x 420mm)"], colors: ["Full Colour"], material: "Premium 250gsm matte art paper", edition: "Hand-numbered limited edition", includes: "Cardboard backing, protective sleeve", care: "Store flat, frame to preserve", brand: "SCSTix Collectibles", taxPct: 20 },
  { id: 14, name: "Mini Trophy Replica", sku: "COL-TRP-01", category: "Collectibles", price: 79.99, stock: 9, emoji: "🏆", featured: true, description: "Die-cast trophy replica, 1:5 scale. Gold plated finish.", discount: 0, sizes: ["1:5 Scale (28cm tall)"], colors: ["Gold"], material: "Zinc alloy, gold plated", weight: "850g", includes: "Display stand, dust cloth, gift box", care: "Dust regularly, avoid moisture", brand: "SCSTix Collectibles", taxPct: 20 },

  /* Dresses — full attributes: brand, stock (qty), Size / Color / Material via dynamic_attributes + sizes/colors */
  { id: 15, name: "Evening Midi Dress", sku: "DRS-EVN-01", barcode: "5051000000015", category: "Dresses", price: 72.99, stock: 48, emoji: "👗", featured: true, returnable: true, taxPct: 20, brand: "Luna Atelier", discount: 0, description: "Elegant midi length with subtle sheen. Lined bodice, concealed back zip.", care: "Dry clean only", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Navy", "Burgundy"], material: "Shell: 92% Polyester, 8% Elastane · Lining: 100% Polyester", dynamic_attributes: { Size: ["XS", "S", "M", "L", "XL"], Color: ["Black", "Navy", "Burgundy"], Material: ["Satin blend (listed)", "Crepe blend"] } },
  { id: 16, name: "Summer Floral Dress", sku: "DRS-FLR-02", barcode: "5051000000016", category: "Dresses", price: 54.5, stock: 62, emoji: "🌸", featured: true, returnable: true, taxPct: 20, brand: "Bloom & Thread", discount: 0, description: "Lightweight floral print, adjustable straps, tiered skirt.", care: "Machine wash 30°C", sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Coral", "Sky Blue", "White"], material: "100% Viscose", dynamic_attributes: { Size: ["XS", "S", "M", "L", "XL", "XXL"], Color: ["Coral", "Sky Blue", "White"], Material: ["Viscose", "Organic cotton poplin"] } },
  { id: 17, name: "Office Shift Dress", sku: "DRS-OFF-03", barcode: "5051000000017", category: "Dresses", price: 64.0, stock: 35, emoji: "💼", featured: false, returnable: true, taxPct: 20, brand: "Nine-to-Five", discount: 0, description: "Structured shift with side pockets, knee length, wrinkle-resistant.", care: "Machine wash 40°C", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Charcoal", "Camel", "Black"], material: "68% Polyester, 29% Viscose, 3% Elastane", dynamic_attributes: { Size: ["XS", "S", "M", "L", "XL"], Color: ["Charcoal", "Camel", "Black"], Material: ["Stretch suiting", "Ponte knit"] } },
  { id: 18, name: "Casual Denim Dress", sku: "DRS-DNM-04", barcode: "5051000000018", category: "Dresses", price: 49.99, stock: 55, emoji: "👖", featured: true, returnable: true, taxPct: 20, brand: "Denim Lane", discount: 0, description: "Classic shirt-dress cut in mid-weight denim, belt included.", care: "Machine wash cold", sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Indigo", "Light Blue", "Black"], material: "98% Cotton, 2% Elastane", dynamic_attributes: { Size: ["XS", "S", "M", "L", "XL", "XXL"], Color: ["Indigo", "Light Blue", "Black"], Material: ["Stretch denim", "Rigid denim"] } },
  { id: 19, name: "Maxi Boho Dress", sku: "DRS-BOH-05", barcode: "5051000000019", category: "Dresses", price: 58.75, stock: 40, emoji: "🌿", featured: false, returnable: true, taxPct: 20, brand: "Wanderlust", discount: 0, description: "Flowing maxi with smocked bodice and flutter sleeves.", care: "Machine wash 30°C", sizes: ["S", "M", "L", "XL"], colors: ["Olive", "Rust", "Cream"], material: "100% Rayon", dynamic_attributes: { Size: ["S", "M", "L", "XL"], Color: ["Olive", "Rust", "Cream"], Material: ["Rayon crepe", "Viscose challis"] } },
  { id: 20, name: "Bodycon Cocktail Dress", sku: "DRS-CT-06", barcode: "5051000000020", category: "Dresses", price: 69.0, stock: 28, emoji: "✨", featured: true, returnable: true, taxPct: 20, brand: "After Eight", discount: 0, description: "Figure-hugging cocktail length, ruched side seam.", care: "Hand wash cold", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Ruby", "Emerald", "Black"], material: "90% Polyester, 10% Spandex", dynamic_attributes: { Size: ["XS", "S", "M", "L", "XL"], Color: ["Ruby", "Emerald", "Black"], Material: ["Jersey knit", "Scuba"] } },
  { id: 21, name: "Linen Shirt Dress", sku: "DRS-LIN-07", barcode: "5051000000021", category: "Dresses", price: 61.5, stock: 33, emoji: "🌾", featured: false, returnable: true, taxPct: 20, brand: "Coastal Linen Co.", discount: 0, description: "Breathable linen blend, button front, roll-tab sleeves.", care: "Machine wash 30°C, reshape while damp", sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Natural", "White", "Soft Blue"], material: "55% Linen, 45% Cotton", dynamic_attributes: { Size: ["XS", "S", "M", "L", "XL", "XXL"], Color: ["Natural", "White", "Soft Blue"], Material: ["Linen-cotton", "Pure linen"] } },
  { id: 22, name: "Wrap Dress Classic", sku: "DRS-WRP-08", barcode: "5051000000022", category: "Dresses", price: 56.25, stock: 44, emoji: "🎀", featured: true, returnable: true, taxPct: 20, brand: "Silhouette", discount: 0, description: "True wrap closure, tie waist, knee length.", care: "Machine wash 30°C", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Navy Dot", "Red", "Black"], material: "95% Polyester, 5% Elastane", dynamic_attributes: { Size: ["XS", "S", "M", "L", "XL"], Color: ["Navy Dot", "Red", "Black"], Material: ["ITY knit", "Matte jersey"] } },
  { id: 23, name: "Kids Party Dress", sku: "DRS-KID-09", barcode: "5051000000023", category: "Dresses", price: 32.99, stock: 70, emoji: "🎈", featured: false, returnable: true, taxPct: 20, brand: "Little Sparkle", discount: 0, description: "Party dress with tulle skirt, soft cotton bodice, glitter trim.", care: "Machine wash 30°C inside out", sizes: ["4Y", "5Y", "6Y", "7Y", "8Y", "10Y", "12Y"], colors: ["Pink", "Lilac", "Gold"], material: "Bodice: 100% Cotton · Skirt: Polyester tulle", dynamic_attributes: { Size: ["4Y", "5Y", "6Y", "7Y", "8Y", "10Y", "12Y"], Color: ["Pink", "Lilac", "Gold"], Material: ["Cotton + tulle", "Satin + tulle"] } },
  { id: 24, name: "Bridesmaid Dress", sku: "DRS-BRD-10", barcode: "5051000000024", category: "Dresses", price: 95.0, stock: 22, emoji: "💐", featured: true, returnable: true, taxPct: 20, brand: "Vow Studio", discount: 0, description: "Floor-length chiffon overlay, padded cups, invisible zip.", care: "Dry clean recommended", sizes: ["XS", "S", "M", "L", "XL", "XXL"], colors: ["Dusty Rose", "Sage", "Champagne"], material: "Shell: 100% Polyester chiffon · Lining: 100% Polyester", dynamic_attributes: { Size: ["XS", "S", "M", "L", "XL", "XXL"], Color: ["Dusty Rose", "Sage", "Champagne"], Material: ["Chiffon", "Soft satin"] } },
];

export const INITIAL_USERS = [
  { id: 1, name: "Alex Rivera", email: "admin@fanstore.com", password: "admin123", role: "admin", avatar: "AR", phone: "07700900001", active: true, joinDate: "2023-01-01", loyaltyPoints: 0, tier: "N/A" },
  { id: 2, name: "Sam Chen", email: "manager@fanstore.com", password: "mgr123", role: "manager", avatar: "SC", phone: "07700900002", active: true, joinDate: "2023-01-15", loyaltyPoints: 0, tier: "N/A" },
  { id: 3, name: "Jordan Lee", email: "cashier@fanstore.com", password: "cash123", role: "cashier", counter: "Counter 1", avatar: "JL", phone: "07700900003", active: true, joinDate: "2023-03-01", loyaltyPoints: 0, tier: "N/A" },
  { id: 4, name: "Morgan Blake", email: "cashier2@fanstore.com", password: "cash456", role: "cashier", counter: "Counter 2", avatar: "MB", phone: "07700900004", active: true, joinDate: "2023-04-01", loyaltyPoints: 0, tier: "N/A" },
  { id: 5, name: "Taylor Smith", email: "customer@fanstore.com", password: "cust123", role: "customer", avatar: "TS", phone: "07700900005", active: true, joinDate: "2023-06-01", loyaltyPoints: 320, tier: "Silver", pointsExpiry: "2025-06-01", totalSpent: 1240 },
  { id: 6, name: "Chris Johnson", email: "chris@email.com", password: "cust456", role: "customer", avatar: "CJ", phone: "07700900006", active: true, joinDate: "2023-09-01", loyaltyPoints: 45, tier: "Bronze", pointsExpiry: "2025-09-01", totalSpent: 180 },
  { id: 7, name: "Alex Murphy", email: "staff1@fanstore.com", password: "staff123", role: "staff", avatar: "AM", phone: "07700900007", active: true, joinDate: "2024-01-01", counter: "Counter 1", loyaltyPoints: 0, tier: "N/A" },
  { id: 8, name: "Jamie Davis", email: "staff2@fanstore.com", password: "staff456", role: "staff", avatar: "JD", phone: "07700900008", active: true, joinDate: "2024-02-01", counter: "Counter 2", loyaltyPoints: 0, tier: "N/A" },
];

export const INITIAL_ORDERS = [
  { id: "ORD-0001", customerId: 5, customerName: "Taylor Smith", cashierId: 3, cashierName: "Jordan Lee", items: [{ productId: 1, name: "Home Jersey 2024", qty: 1, price: 89.99, discount: 0 }, { productId: 6, name: "Football Scarf", qty: 2, price: 19.99, discount: 0 }], subtotal: 129.97, tax: 25.99, discountAmt: 0, loyaltyDiscount: 0, deliveryCharge: 0, total: 155.96, payment: "Card", cardLast4: "4242", date: "2024-01-15 10:23", counter: "Counter 1", status: "completed", orderType: "in-store", loyaltyEarned: 155, loyaltyUsed: 0 },
  { id: "ORD-0002", customerId: 6, customerName: "Chris Johnson", cashierId: 4, cashierName: "Morgan Blake", items: [{ productId: 9, name: "Match Ball Official", qty: 1, price: 129.99, discount: 0 }], subtotal: 129.99, tax: 26.00, discountAmt: 0, loyaltyDiscount: 0, deliveryCharge: 0, total: 155.99, payment: "Cash", cashGiven: 160, cashChange: 4.01, date: "2024-01-15 11:45", counter: "Counter 2", status: "completed", orderType: "in-store", loyaltyEarned: 155, loyaltyUsed: 0 },
  { id: "ORD-0003", customerId: null, customerName: "Walk-in", cashierId: 3, cashierName: "Jordan Lee", items: [{ productId: 4, name: "Training Jacket", qty: 1, price: 64.99, discount: 0 }, { productId: 7, name: "Team Cap", qty: 1, price: 24.99, discount: 0 }], subtotal: 89.98, tax: 18.00, discountAmt: 0, loyaltyDiscount: 0, deliveryCharge: 0, total: 107.98, payment: "Card", cardLast4: "1234", date: "2024-01-15 13:12", counter: "Counter 1", status: "completed", orderType: "in-store", loyaltyEarned: 0, loyaltyUsed: 0 },
  { id: "ORD-0004", customerId: 5, customerName: "Taylor Smith", cashierId: 3, cashierName: "Jordan Lee", items: [{ productId: 12, name: "Signed Jersey", qty: 1, price: 249.99, discount: 0 }], subtotal: 249.99, tax: 50.00, discountAmt: 0, loyaltyDiscount: 0, deliveryCharge: 5.99, total: 305.98, payment: "QR", date: "2024-01-14 14:05", counter: "Counter 1", status: "completed", orderType: "delivery", deliveryAddress: "123 Stadium Road, London", deliveryStatus: "delivered", loyaltyEarned: 305, loyaltyUsed: 0 },
  { id: "ORD-0005", customerId: 5, customerName: "Taylor Smith", cashierId: 4, cashierName: "Morgan Blake", items: [{ productId: 2, name: "Away Jersey 2024", qty: 2, price: 89.99, discount: 0 }, { productId: 8, name: "Fan Hoodie", qty: 1, price: 54.99, discount: 0 }], subtotal: 234.97, tax: 47.00, discountAmt: 0, loyaltyDiscount: 0, deliveryCharge: 0, total: 281.97, payment: "Cash", cashGiven: 300, cashChange: 18.03, date: "2024-01-14 09:30", counter: "Counter 2", status: "completed", orderType: "in-store", loyaltyEarned: 281, loyaltyUsed: 0 },
  { id: "ORD-0006", customerId: 6, customerName: "Chris Johnson", cashierId: 3, cashierName: "Jordan Lee", items: [{ productId: 10, name: "Goalkeeper Gloves", qty: 1, price: 44.99, discount: 0 }, { productId: 11, name: "Shin Guards Pro", qty: 2, price: 29.99, discount: 0 }], subtotal: 104.97, tax: 21.00, discountAmt: 0, loyaltyDiscount: 0, deliveryCharge: 0, total: 125.97, payment: "Card", cardLast4: "9999", date: "2024-01-13 11:20", counter: "Counter 1", status: "refunded", orderType: "in-store", loyaltyEarned: 0, loyaltyUsed: 0 },
  { id: "ORD-0007", customerId: 5, customerName: "Taylor Smith", cashierId: null, cashierName: "Online", items: [{ productId: 1, name: "Home Jersey 2024", qty: 1, price: 89.99, discount: 0 }, { productId: 6, name: "Football Scarf", qty: 1, price: 19.99, discount: 0 }], subtotal: 109.98, tax: 22.00, discountAmt: 0, loyaltyDiscount: 0, deliveryCharge: 3.99, total: 135.97, payment: "Online", date: "2024-01-16 09:10", counter: "Online", status: "preparing", orderType: "delivery", deliveryAddress: "45 King Street, London, E1 7PQ", deliveryZone: "London Zone 1", deliveryStatus: "pending", loyaltyEarned: 135, loyaltyUsed: 0, trackingStage: 1 },
  { id: "ORD-0008", customerId: 6, customerName: "Chris Johnson", cashierId: null, cashierName: "Online", items: [{ productId: 7, name: "Team Cap", qty: 2, price: 24.99, discount: 0 }, { productId: 8, name: "Fan Hoodie", qty: 1, price: 54.99, discount: 0 }], subtotal: 104.97, tax: 21.00, discountAmt: 0, loyaltyDiscount: 0, deliveryCharge: 0, total: 125.97, payment: "Online", date: "2024-01-16 11:30", counter: "Online", status: "preparing", orderType: "pickup", loyaltyEarned: 125, loyaltyUsed: 0, trackingStage: 1 },
  { id: "ORD-0009", customerId: 5, customerName: "Taylor Smith", cashierId: null, cashierName: "Online", items: [{ productId: 12, name: "Signed Jersey", qty: 1, price: 249.99, discount: 15 }], subtotal: 212.49, tax: 42.50, discountAmt: 37.50, loyaltyDiscount: 0, deliveryCharge: 5.99, total: 260.98, payment: "Online", date: "2024-01-16 14:00", counter: "Online", status: "completed", orderType: "delivery", deliveryAddress: "78 Stadium Rd, London EC1A 2BB", deliveryZone: "London Zone 1", deliveryStatus: "delivered", loyaltyEarned: 260, loyaltyUsed: 0, trackingStage: 3 },
  { id: "ORD-PKUP-001", customerId: 5, customerName: "Taylor Smith", cashierId: null, cashierName: "Online", items: [{ productId: 1, name: "Home Jersey 2024", qty: 1, price: 89.99, discount: 0 }], subtotal: 89.99, tax: 18.00, total: 107.99, payment: "Online", date: "2024-03-18 10:00", counter: "Online", status: "pending", orderType: "pickup" },
  { id: "ORD-PKUP-002", customerId: 6, customerName: "Chris Johnson", cashierId: null, cashierName: "Online", items: [{ productId: 4, name: "Training Jacket", qty: 1, price: 64.99, discount: 0 }], subtotal: 64.99, tax: 13.00, total: 77.99, payment: "Online", date: "2024-03-18 11:00", counter: "Online", status: "picked-up", orderType: "pickup", pickedUpAt: "2024-03-18 11:30", pickedUpBy: "Staff Alex" },
];

export const INITIAL_RETURNS = [
  { id: "RET-001", orderId: "ORD-0006", customerId: 6, customerName: "Chris Johnson", productId: 10, productName: "Goalkeeper Gloves", qty: 1, reason: "Wrong size", status: "approved", refundAmount: 44.99, date: "2024-01-16 09:00", type: "full" },
  { id: "RET-002", orderId: "ORD-0001", customerId: 5, customerName: "Taylor Smith", productId: 6, productName: "Football Scarf", qty: 1, reason: "Damaged item", status: "pending", refundAmount: 19.99, date: "2024-01-16 14:30", type: "partial" },
];

export const INITIAL_BANNERS = [
  { id: 1, title: "Match Day Special!", subtitle: "20% off all Jerseys today only", cta: "Shop Now", color: "#dc2626", grad: "linear-gradient(135deg,#dc2626,#7f1d1d)", emoji: "⚽", active: true, offerType: "category", offerTarget: "Jerseys", offerDiscount: 20, startDate: "2024-01-01T00:00", endDate: "2026-12-31T23:59", image: "https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg?auto=compress&cs=tinysrgb&w=1600" },
  { id: 2, title: "New Season Arrivals", subtitle: "2024 kits now in stock", cta: "Explore", color: "#2563eb", grad: "linear-gradient(135deg,#2563eb,#1e3a8a)", emoji: "🆕", active: true, offerType: "none", offerTarget: "", offerDiscount: 0, startDate: "2024-01-01T00:00", endDate: "2026-12-31T23:59", image: "https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=1600" },
  { id: 3, title: "Loyalty Rewards", subtitle: "Earn & redeem points every visit", cta: "Join Now", color: "#16a34a", grad: "linear-gradient(135deg,#16a34a,#14532d)", emoji: "🏆", active: false, offerType: "none", offerTarget: "", offerDiscount: 0, startDate: "2024-01-01T00:00", endDate: "2026-12-31T23:59", image: "https://images.pexels.com/photos/1884574/pexels-photo-1884574.jpeg?auto=compress&cs=tinysrgb&w=1600" },
  { id: 4, title: "Collectibles Sale", subtitle: "15% off signed memorabilia", cta: "Shop", color: "#7c3aed", grad: "linear-gradient(135deg,#7c3aed,#4c1d95)", emoji: "✍️", active: true, offerType: "category", offerTarget: "Collectibles", offerDiscount: 15, startDate: "2024-01-01T00:00", endDate: "2026-12-31T23:59", image: "https://images.pexels.com/photos/918778/pexels-photo-918778.jpeg?auto=compress&cs=tinysrgb&w=1600" },
];

export const INITIAL_COUPONS = [
  { id: 1, code: "FANDAY10", description: "10% off everything", type: "percent", value: 10, minOrder: 0, maxUses: 100, uses: 23, active: true, expiry: "2026-12-31" },
  { id: 2, code: "WELCOME20", description: "£20 off for new customers", type: "fixed", value: 20, minOrder: 50, maxUses: 50, uses: 12, active: true, expiry: "2026-12-31" },
  { id: 3, code: "FREESHIP", description: "Free delivery", type: "delivery", value: 100, minOrder: 30, maxUses: 200, uses: 67, active: true, expiry: "2026-12-31" },
];

export const INITIAL_COUNTERS = [
  { id: "c1", name: "Counter 1", location: "Main Entrance", active: true },
  { id: "c2", name: "Counter 2", location: "East Wing", active: true },
  { id: "c3", name: "Counter 3", location: "VIP Section", active: false },
];

export const INITIAL_SETTINGS = {
  storeName: "SCSTix EPOS",
  storeAddress: "Venue Address, London, EC1A 1BB",
  storePhone: "020 7946 0800",
  storeEmail: "hello@scstix.com",
  currency: "GBP", sym: "£",
  loyaltyRate: 1, loyaltyValue: 0.01,
  receiptFooter: "Thank you for your purchase! Come back soon.",
  allowReturns: true, returnDays: 30,
  deliveryZones: [
    { zone: "London Zone 1", charge: 3.99, days: 1 },
    { zone: "London Zone 2", charge: 5.99, days: 2 },
    { zone: "UK Nationwide", charge: 9.99, days: 3 },
  ],
  selfServiceEnabled: false,
};

export const INITIAL_PARKED = [];

export const CATEGORIES = ["All", "Jerseys", "Training Wear", "Fan Accessories", "Football Equipment", "Collectibles", "Dresses"];

export const TIER_CONFIG = {
  Bronze: { min: 0, max: 499, color: "#cd7f32", bg: "#2a1a0a", label: "Bronze", icon: "🥉" },
  Silver: { min: 500, max: 1499, color: "#9ca3af", bg: "#1a1f2a", label: "Silver", icon: "🥈" },
  Gold: { min: 1500, max: Infinity, color: "#f59e0b", bg: "#2a1e00", label: "Gold", icon: "🥇" },
};
